services:

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
    depends_on:
      - mongo

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379"
    command: redis-server --maxmemory 200mb --maxmemory-policy allkeys-lru

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://admin:admin123@mongo:27017/?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_REFRESH_SECRET=Nc/2vCmtlXcTNqY+ipCNp0DT6Gg
      - JWT_ACCESS_SECRET=bKLIUw4cVhI6XyEJkhh030l3JaU
    depends_on:
      - mongo
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  mongo_data:
